server:
  port: 8080
spring:
  application:
    name: glowworm
  profiles:
    active: dev
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:cn/jihangyu/glowworm/**/**.xml
  type-aliases-package: classpath:cn.jihangyu.glowworm.**.entity
#log
logging:
  config: classpath:logback.xml
